AWSTemplateFormatVersion: "2010-09-09"
Description: Static website hosting for Vite React app with S3 and CloudFront

Parameters:
  BucketPrefix:
    Type: String
    Description: Prefix for the S3 bucket name (must be lowercase, no spaces)
    Default: cbus-customerexplorer-ui

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${BucketPrefix}-bucket"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${FrontendBucket.Arn}/*"
            Condition:
              StringEquals:
                "aws:Referer": "cloudfront.amazonaws.com"

  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        PriceClass: PriceClass_100

Outputs:
  BucketName:
    Value: !Ref FrontendBucket
  CloudFrontDistributionId:
    Value: !Ref FrontendDistribution
  CloudFrontDomainName:
    Value: !GetAtt FrontendDistribution.DomainName
